spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: egormalov.2007@gmail.com
    password:
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: User-Service
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    url: jdbc:postgresql://localhost:5432/avanza_natural
    user: postgres
    password: password
    baseline-on-migrate: true
    create-schemas: true
    default-schema: users
  datasource:
    url: jdbc:postgresql://localhost:5432/avanza_natural
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
web:
  service:
    uri: http://localhost:3000

resilience4j:
  ratelimiter:
    instances:
      userLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
      confirmationCodeLimiter:
        limit-for-period: 5
        limitRefreshPeriod: 1s
  circuitbreaker:
    instances:
      identityClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always